// Real SQLite constraints/aggregates, real auth, and privacy/validation boundaries.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { DatabaseSync } = require('node:sqlite');
(async () => {
  const lib = await import('data:text/javascript;base64,' + Buffer.from(fs.readFileSync('functions/api/_lib.js', 'utf8')).toString('base64'));
  const source = fs.readFileSync('functions/api/traffic.js', 'utf8').replace("import { json, isAdmin } from './_lib.js';", 'const { json, isAdmin } = globalThis.trafficLib;');
  globalThis.trafficLib = lib;
  const api = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
  const sql = new DatabaseSync(':memory:'); sql.exec(fs.readFileSync('scripts/traffic-schema.sql', 'utf8'));
  const db = { prepare(text) { let args = []; return { bind(...values) { args = values; return this; }, run() { const s = sql.prepare(text); return { results: text.startsWith('SELECT') ? s.all(...args) : (s.run(...args), []) }; } }; }, async batch(statements) { return statements.map(s => s.run()); } };
  const env = { JP_TRAFFIC: db, TOTP_SECRET: 'LOCAL-TEST-ONLY' };
  const { token } = await lib.issueSession(env);
  const url = 'https://jimmypark.net/api/traffic';
  const visitor = crypto.randomUUID(), event = crypto.randomUUID();
  const body = { visitor, event, path: '/work', referrer: 'https://www.google.com', utm: '' };
  const post = (data = body, headers = {}) => api.onRequestPost({ env, request: new Request(url, { method: 'POST', headers: { Origin: 'https://jimmypark.net', 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(data) }) });
  const get = date => api.onRequestGet({ env, request: new Request(url + (date ? '?date=' + date : ''), { headers: { Authorization: 'Bearer ' + token } }) });
  assert.equal(api.dayAt(Date.parse('2026-10-01T14:59:59Z')), '2026-10-01');
  assert.equal(api.dayAt(Date.parse('2026-10-01T15:00:00Z')), '2026-10-02');
  assert.equal((await api.onRequestGet({ env, request: new Request(url) })).status, 401);
  assert.equal((await post(body, { Origin: 'https://evil.example' })).status, 403);
  assert.equal((await post({ ...body, path: '/admin' })).status, 400);
  assert.equal((await post({ ...body, path: '/search?q=private' })).status, 400);
  assert.equal((await post(body, { DNT: '1' })).status, 204);
  assert.equal((await post(body, { 'Sec-GPC': '1' })).status, 204);
  assert.equal((await post(body, { 'User-Agent': 'Googlebot' })).status, 204);
  assert.equal(sql.prepare('SELECT COUNT(*) n FROM traffic_views').get().n, 0);
  assert.equal((await post()).status, 204); assert.equal((await post()).status, 204);
  assert.equal((await post({ ...body, event: crypto.randomUUID(), path: '/dev', referrer: 'https://instagram.com' })).status, 204);
  assert.equal((await post({ ...body, visitor: crypto.randomUUID(), event: crypto.randomUUID(), referrer: '', utm: 'linkedin' })).status, 204);
  const data = await (await get()).json();
  assert.equal(data.visitors, 2); assert.equal(data.views, 3); assert.equal(data.daily.length, 14);
  assert.equal(data.sources.find(r => r.source === 'Google').visitors, 1);
  assert.equal(data.landings[0].path, '/work'); assert.equal(data.landings[0].visitors, 2);
  assert.equal(api.sourceOf('https://secret.example/path?q=secret', ''), 'Other referral');
  assert.equal(api.sourceOf('https://jimmypark.net/work', ''), 'Direct / unknown');
  assert.equal((await get('2026-02-30')).status, 400);
  assert.equal((await get('2099-01-01')).status, 400);
  assert.equal((await post(body, { Authorization: 'Bearer ' + token })).status, 204);
  assert.equal(sql.prepare('SELECT COUNT(*) n FROM traffic_views').get().n, 3);
  sql.prepare('INSERT INTO traffic_visitors VALUES(?,?,?,?)').run('2000-01-01', crypto.randomUUID(), 'Direct / unknown', '/');
  await post(); assert.equal(sql.prepare("SELECT COUNT(*) n FROM traffic_visitors WHERE day='2000-01-01'").get().n, 0);
  assert.equal(JSON.stringify(data).includes(visitor), false);
  // Execute the actual client recorder with a tiny browser surface.
  const recorder = fs.readFileSync('assets/site.js', 'utf8').split('  // ── Active nav')[0] + '\n})();';
  let sent = [], storage = new Map();
  const sandbox = { location: { hostname: 'jimmypark.net', pathname: '/work', search: '?utm_source=instagram&private=secret' }, navigator: {}, crypto, URLSearchParams, URL, Date, JSON, localStorage: { getItem: k => storage.get(k), setItem: (k,v) => storage.set(k,v) }, document: { referrer: 'https://google.com/search?q=secret', body: { getAttribute: () => 'work' }, documentElement: { classList: { add() {} } } }, fetch: (u,o) => { sent.push(JSON.parse(o.body)); return Promise.resolve(); } };
  sandbox.window = sandbox; sandbox.top = sandbox; vm.runInNewContext(recorder, sandbox); vm.runInNewContext(recorder, sandbox);
  assert.equal(sent.length, 2); assert.equal(sent[0].visitor, sent[1].visitor); assert.notEqual(sent[0].event, sent[1].event);
  assert.equal(sent[0].referrer, 'https://google.com'); assert.equal(JSON.stringify(sent).includes('secret'), false);
  sandbox.navigator.globalPrivacyControl = true; vm.runInNewContext(recorder, sandbox); assert.equal(sent.length, 2);
  sandbox.navigator.globalPrivacyControl = false; sandbox.location.search = '?preview=1'; vm.runInNewContext(recorder, sandbox); assert.equal(sent.length, 2);
  console.log('PASS traffic: KST, real SQLite dedup/first-source/retention, auth, privacy, client guards');
})().catch(err => { console.error(err); process.exitCode = 1; });
